## **행정동**

### **1. 생활인구_내국인**

In [ ]:
import os
import pandas as pd
import itertools

In [ ]:
path = "C:/Users/ZzAa/Desktop/대학원 (24-1)/데이터마이닝/Project/Data/행정동"
os.chdir(path)

print("Current Working Directory:", os.getcwd())

# load baseline data
dong_time = pd.read_csv('한강공원별시군구행정동_날짜순.csv')
dong_time

In [ ]:
# Define the aggregation function
def aggregate_data(df):
    return df.groupby(['기준일ID', '행정동코드']).agg({
        '총생활인구수': 'sum',
        '남자0세부터9세생활인구수': 'sum',
        '남자10세부터14세생활인구수': 'sum',
        '남자15세부터19세생활인구수': 'sum',
        '남자20세부터24세생활인구수': 'sum',
        '남자25세부터29세생활인구수': 'sum',
        '남자30세부터34세생활인구수': 'sum',
        '남자35세부터39세생활인구수': 'sum',
        '남자40세부터44세생활인구수': 'sum',
        '남자45세부터49세생활인구수': 'sum',
        '남자50세부터54세생활인구수': 'sum',
        '남자55세부터59세생활인구수': 'sum',
        '남자60세부터64세생활인구수': 'sum',
        '남자65세부터69세생활인구수': 'sum',
        '남자70세이상생활인구수': 'sum',
        '여자0세부터9세생활인구수': 'sum',
        '여자10세부터14세생활인구수': 'sum',
        '여자15세부터19세생활인구수': 'sum',
        '여자20세부터24세생활인구수': 'sum',
        '여자25세부터29세생활인구수': 'sum',
        '여자30세부터34세생활인구수': 'sum',
        '여자35세부터39세생활인구수': 'sum',
        '여자40세부터44세생활인구수': 'sum',
        '여자45세부터49세생활인구수': 'sum',
        '여자50세부터54세생활인구수': 'sum',
        '여자55세부터59세생활인구수': 'sum',
        '여자60세부터64세생활인구수': 'sum',
        '여자65세부터69세생활인구수': 'sum',
        '여자70세이상생활인구수': 'sum'
    }).reset_index()

# List of file paths for each dataset
file_paths_2020 = ['LOCAL_PEOPLE_DONG_202001.csv', 'LOCAL_PEOPLE_DONG_202002.csv', 'LOCAL_PEOPLE_DONG_202003.csv', 'LOCAL_PEOPLE_DONG_202004.csv', 'LOCAL_PEOPLE_DONG_202005.csv', 'LOCAL_PEOPLE_DONG_202006.csv', 'LOCAL_PEOPLE_DONG_202007.csv', 'LOCAL_PEOPLE_DONG_202008.csv', 'LOCAL_PEOPLE_DONG_202009.csv', 'LOCAL_PEOPLE_DONG_202010.csv', 'LOCAL_PEOPLE_DONG_202011.csv', 'LOCAL_PEOPLE_DONG_202012.csv']
file_paths_2021 = ['LOCAL_PEOPLE_DONG_202101.csv', 'LOCAL_PEOPLE_DONG_202102.csv', 'LOCAL_PEOPLE_DONG_202103.csv', 'LOCAL_PEOPLE_DONG_202104.csv', 'LOCAL_PEOPLE_DONG_202105.csv', 'LOCAL_PEOPLE_DONG_202106.csv', 'LOCAL_PEOPLE_DONG_202107.csv', 'LOCAL_PEOPLE_DONG_202108.csv', 'LOCAL_PEOPLE_DONG_202109.csv', 'LOCAL_PEOPLE_DONG_202110.csv', 'LOCAL_PEOPLE_DONG_202111.csv', 'LOCAL_PEOPLE_DONG_202112.csv']
file_paths_2022 = ['LOCAL_PEOPLE_DONG_202201.csv', 'LOCAL_PEOPLE_DONG_202202.csv', 'LOCAL_PEOPLE_DONG_202203.csv', 'LOCAL_PEOPLE_DONG_202204.csv', 'LOCAL_PEOPLE_DONG_202205.csv', 'LOCAL_PEOPLE_DONG_202206.csv', 'LOCAL_PEOPLE_DONG_202207.csv', 'LOCAL_PEOPLE_DONG_202208.csv', 'LOCAL_PEOPLE_DONG_202209.csv', 'LOCAL_PEOPLE_DONG_202210.csv', 'LOCAL_PEOPLE_DONG_202211.csv', 'LOCAL_PEOPLE_DONG_202212.csv']
file_paths_2023 = ['LOCAL_PEOPLE_DONG_202301.csv', 'LOCAL_PEOPLE_DONG_202302.csv', 'LOCAL_PEOPLE_DONG_202303.csv', 'LOCAL_PEOPLE_DONG_202304.csv', 'LOCAL_PEOPLE_DONG_202305.csv']

# Function to load, aggregate and return the dataframe for each file
def load_and_aggregate(file_path):
    df = pd.read_csv(file_path, index_col=False)
    return aggregate_data(df)

# Process each file in 2020
aggregated_data_2020 = [load_and_aggregate(file) for file in file_paths_2020]
# Process each file in 2021
aggregated_data_2021 = [load_and_aggregate(file) for file in file_paths_2021]
# Process each file in 2022
aggregated_data_2022 = [load_and_aggregate(file) for file in file_paths_2022]
# Process each file in 2023
aggregated_data_2023 = [load_and_aggregate(file) for file in file_paths_2023]

In [ ]:
# Combine all dataframes into a single dataframe for each year
combined_2020 = pd.concat(aggregated_data_2020, ignore_index=True)
combined_2021 = pd.concat(aggregated_data_2021, ignore_index=True)
combined_2022 = pd.concat(aggregated_data_2022, ignore_index=True)
combined_2023 = pd.concat(aggregated_data_2023, ignore_index=True)

In [ ]:
# Combine all data
local_all = pd.concat([combined_2020, combined_2021, combined_2022, combined_2023], ignore_index=True)
local_all

- Rename variables

In [ ]:
# Define the new column names
new_column_names = {
    '기준일ID': 'DATE',
    '행정동코드': 'adm_cd',
    '총생활인구수': 'total_local',
    '남자0세부터9세생활인구수': 'male_0_9',
    '남자10세부터14세생활인구수': 'male_10_14',
    '남자15세부터19세생활인구수': 'male_15_19',
    '남자20세부터24세생활인구수': 'male_20_24',
    '남자25세부터29세생활인구수': 'male_25_29',
    '남자30세부터34세생활인구수': 'male_30_34',
    '남자35세부터39세생활인구수': 'male_35_39',
    '남자40세부터44세생활인구수': 'male_40_44',
    '남자45세부터49세생활인구수': 'male_45_49',
    '남자50세부터54세생활인구수': 'male_50_54',
    '남자55세부터59세생활인구수': 'male_55_59',
    '남자60세부터64세생활인구수': 'male_60_64',
    '남자65세부터69세생활인구수': 'male_65_69',
    '남자70세이상생활인구수': 'male_70_above',
    '여자0세부터9세생활인구수': 'female_0_9',
    '여자10세부터14세생활인구수': 'female_10_14',
    '여자15세부터19세생활인구수': 'female_15_19',
    '여자20세부터24세생활인구수': 'female_20_24',
    '여자25세부터29세생활인구수': 'female_25_29',
    '여자30세부터34세생활인구수': 'female_30_34',
    '여자35세부터39세생활인구수': 'female_35_39',
    '여자40세부터44세생활인구수': 'female_40_44',
    '여자45세부터49세생활인구수': 'female_45_49',
    '여자50세부터54세생활인구수': 'female_50_54',
    '여자55세부터59세생활인구수': 'female_55_59',
    '여자60세부터64세생활인구수': 'female_60_64',
    '여자65세부터69세생활인구수': 'female_65_69',
    '여자70세이상생활인구수': 'female_70_above'
}

# Rename the columns
local_all.rename(columns=new_column_names, inplace=True)

# Check dataframe
local_all

- Convert `int` to `Datetime`

In [ ]:
# baseline data
dong_time['DATE'] = pd.to_datetime(dong_time['DATE'], format = '%Y-%m-%d')
dong_time

In [ ]:
# local data
local_all['DATE'] = pd.to_datetime(local_all['DATE'], format = '%Y%m%d')
local_all

- 한강공원별시군구행정동_날짜순 + 생활인구_내국인

In [ ]:
merged_data = pd.merge(dong_time, local_all, on=['adm_cd', 'DATE'], how='left')
merged_data

### **2. 생활인구_단기체류외국인**

In [ ]:
# Define the aggregation function
def aggregate_data(df):
    return df.groupby(['기준일ID', '행정동코드']).agg({
        '총생활인구수': 'sum',
        '중국인체류인구수': 'sum',
        '중국외외국인체류인구수': 'sum'
    }).reset_index()

# List of file paths for each dataset
file_paths_2020 = ['TEMP_FOREIGNER_DONG_202001.csv', 'TEMP_FOREIGNER_DONG_202002.csv', 'TEMP_FOREIGNER_DONG_202003.csv', 'TEMP_FOREIGNER_DONG_202004.csv', 'TEMP_FOREIGNER_DONG_202005.csv', 'TEMP_FOREIGNER_DONG_202006.csv', 'TEMP_FOREIGNER_DONG_202007.csv', 'TEMP_FOREIGNER_DONG_202008.csv', 'TEMP_FOREIGNER_DONG_202009.csv', 'TEMP_FOREIGNER_DONG_202010.csv', 'TEMP_FOREIGNER_DONG_202011.csv', 'TEMP_FOREIGNER_DONG_202012.csv']
file_paths_2021 = ['TEMP_FOREIGNER_DONG_202101.csv', 'TEMP_FOREIGNER_DONG_202102.csv', 'TEMP_FOREIGNER_DONG_202103.csv', 'TEMP_FOREIGNER_DONG_202104.csv', 'TEMP_FOREIGNER_DONG_202105.csv', 'TEMP_FOREIGNER_DONG_202106.csv', 'TEMP_FOREIGNER_DONG_202107.csv', 'TEMP_FOREIGNER_DONG_202108.csv', 'TEMP_FOREIGNER_DONG_202109.csv', 'TEMP_FOREIGNER_DONG_202110.csv', 'TEMP_FOREIGNER_DONG_202111.csv', 'TEMP_FOREIGNER_DONG_202112.csv']
file_paths_2022 = ['TEMP_FOREIGNER_DONG_202201.csv', 'TEMP_FOREIGNER_DONG_202202.csv', 'TEMP_FOREIGNER_DONG_202203.csv', 'TEMP_FOREIGNER_DONG_202204.csv', 'TEMP_FOREIGNER_DONG_202205.csv', 'TEMP_FOREIGNER_DONG_202206.csv', 'TEMP_FOREIGNER_DONG_202207.csv', 'TEMP_FOREIGNER_DONG_202208.csv', 'TEMP_FOREIGNER_DONG_202209.csv', 'TEMP_FOREIGNER_DONG_202210.csv', 'TEMP_FOREIGNER_DONG_202211.csv', 'TEMP_FOREIGNER_DONG_202212.csv']
file_paths_2023 = ['TEMP_FOREIGNER_DONG_202301.csv', 'TEMP_FOREIGNER_DONG_202302.csv', 'TEMP_FOREIGNER_DONG_202303.csv', 'TEMP_FOREIGNER_DONG_202304.csv', 'TEMP_FOREIGNER_DONG_202305.csv']

# Function to load, aggregate and return the dataframe for each file
def load_and_aggregate(file_path):
    df = pd.read_csv(file_path, index_col=False)
    return aggregate_data(df)

# Process each file in 2020
aggregated_data_2020 = [load_and_aggregate(file) for file in file_paths_2020]
# Process each file in 2021
aggregated_data_2021 = [load_and_aggregate(file) for file in file_paths_2021]
# Process each file in 2022
aggregated_data_2022 = [load_and_aggregate(file) for file in file_paths_2022]
# Process each file in 2023
aggregated_data_2023 = [load_and_aggregate(file) for file in file_paths_2023]

In [ ]:
# Combine all dataframes into a single dataframe for each year
combined_2020 = pd.concat(aggregated_data_2020, ignore_index=True)
combined_2021 = pd.concat(aggregated_data_2021, ignore_index=True)
combined_2022 = pd.concat(aggregated_data_2022, ignore_index=True)
combined_2023 = pd.concat(aggregated_data_2023, ignore_index=True)

In [ ]:
# Combine all data
temp_all = pd.concat([combined_2020, combined_2021, combined_2022, combined_2023], ignore_index=True)
temp_all

- Rename

In [ ]:
new_column_names = {
    '기준일ID' : 'DATE',
    '행정동코드' : 'adm_cd',
    '총생활인구수' : 'total_temp',
    '중국인체류인구수' : 'chinese',
    '중국외외국인체류인구수' : 'non_chinese'
}

# Rename the columns
temp_all.rename(columns=new_column_names, inplace=True)
temp_all

- Convert `int` to `Datetime`

In [ ]:
# temp data
temp_all['DATE'] = pd.to_datetime(temp_all['DATE'], format = '%Y%m%d')
temp_all

In [ ]:
temp_all.info()

- 한강공원별시군구행정동_날짜순 + 생활인구_내국인 + 생활인구_단기체류외국인

In [ ]:
merged_data = pd.merge(merged_data, temp_all, on=['adm_cd', 'DATE'], how='left')
merged_data

### **3. 소득소비**

In [ ]:
income_data = pd.read_csv('서울시 상권분석서비스(소득소비-행정동).csv', encoding='cp949')
income_data

In [ ]:
# Data structure
income_data.info()

In [ ]:
# Check Null
income_data.isnull().sum()

- Rename

In [ ]:
new_column_names = {
    '기준_년분기_코드' : 'quarter',
    '행정동_코드' : 'adm_cd',
    '월_평균_소득_금액' : 'avg_income',
    '유흥_지출_총금액' : 'drink_cost',
    '여가_문화_지출_총금액' : 'leisure_cost',
    '음식_지출_총금액' : 'food_cost'
}

# Rename the columns
income_data.rename(columns=new_column_names, inplace=True)
income_data

- Drop other variables

In [ ]:
income_data = income_data[['quarter', 'adm_cd', 'avg_income', 'drink_cost', 'leisure_cost', 'food_cost']]
income_data

- Convert `total_cost` to `avg_cost`

In [ ]:
# Function to calculate the number of days in a quarter
def days_in_quarter(year_quarter):
    year = int(str(year_quarter)[:4])
    quarter = int(str(year_quarter)[4])
    if quarter == 1:
        return pd.Timestamp(f"{year}-04-01") - pd.Timestamp(f"{year}-01-01")
    elif quarter == 2:
        return pd.Timestamp(f"{year}-07-01") - pd.Timestamp(f"{year}-04-01")
    elif quarter == 3:
        return pd.Timestamp(f"{year}-10-01") - pd.Timestamp(f"{year}-07-01")
    elif quarter == 4:
        return pd.Timestamp(f"{year+1}-01-01") - pd.Timestamp(f"{year}-10-01")

In [ ]:
# Apply the function to calculate days in quarter
income_data['days_in_quarter'] = income_data['quarter'].apply(days_in_quarter).dt.days

# Divide the costs by the number of days in the quarter
income_data['drink_cost'] = income_data['drink_cost'] / income_data['days_in_quarter']
income_data['leisure_cost'] = income_data['leisure_cost'] / income_data['days_in_quarter']
income_data['food_cost'] = income_data['food_cost'] / income_data['days_in_quarter']

# Drop the auxiliary column
income_data.drop(columns=['days_in_quarter'], inplace=True)
income_data

- Convert `quarter` to `Y-m-d`
    - `merged_data`에 `quarter` 변수를 생성한 후 `adm_cd`, `quarter`를 기준으로 `income_data` 병합

In [ ]:
# Function to convert date to corresponding quarter value
def date_to_quarter(date):
    if date.month in [1, 2, 3]:
        return f"{date.year}1"
    elif date.month in [4, 5, 6]:
        return f"{date.year}2"
    elif date.month in [7, 8, 9]:
        return f"{date.year}3"
    elif date.month in [10, 11, 12]:
        return f"{date.year}4"

# Convert DATE column to datetime format
merged_data['DATE'] = pd.to_datetime(merged_data['DATE'])

# Apply the function to create a new quarter column
merged_data['quarter'] = merged_data['DATE'].apply(date_to_quarter)
merged_data

- Convert `object` to `int`
    - `merged_data`의 `quarter` 변수 형변환

In [ ]:
merged_data['quarter'] = merged_data['quarter'].astype('int64')
merged_data.info()

- 한강공원별시군구행정동_날짜순 + 생활인구_내국인 + 생활인구_단기체류외국인 + 소득소비

In [ ]:
merged_data = pd.merge(merged_data, income_data, on=['adm_cd', 'quarter'], how='left')
merged_data

In [ ]:
# Drop quarter variable
merged_data.drop('quarter', axis=1, inplace=True)

### **4. 행정동 데이터 병합**

In [ ]:
population_income = merged_data.groupby(['AREA_NM', 'DATE'], as_index=False).agg({
    'total_local': 'sum',
    'male_0_9': 'sum',
    'male_10_14': 'sum',
    'male_15_19': 'sum',
    'male_20_24': 'sum',
    'male_25_29': 'sum',
    'male_30_34': 'sum',
    'male_35_39': 'sum',
    'male_40_44': 'sum',
    'male_45_49': 'sum',
    'male_50_54': 'sum',
    'male_55_59': 'sum',
    'male_60_64': 'sum',
    'male_65_69': 'sum',
    'male_70_above': 'sum',
    'female_0_9': 'sum',
    'female_10_14': 'sum',
    'female_15_19': 'sum',
    'female_20_24': 'sum',
    'female_25_29': 'sum',
    'female_30_34': 'sum',
    'female_35_39': 'sum',
    'female_40_44': 'sum',
    'female_45_49': 'sum',
    'female_50_54': 'sum',
    'female_55_59': 'sum',
    'female_60_64': 'sum',
    'female_65_69': 'sum',
    'female_70_above': 'sum',
    'total_temp': 'sum',
    'chinese': 'sum',
    'non_chinese': 'sum',
    'avg_income' : 'mean',
    'drink_cost' : 'sum',
    'leisure_cost' : 'sum',
    'food_cost' : 'sum'
})

population_income

In [ ]:
# 변수명 수정
new_column_names = {
    'AREA_NM' : 'hangang',
    'DATE' : 'date'
}

population_income.rename(columns=new_column_names, inplace=True)
population_income

## 시군구

### **1. 대기환경**

In [ ]:
path = "C:/Users/ZzAa/Desktop/대학원 (24-1)/데이터마이닝/Project/Data/시군구"
os.chdir(path)

print("Current Working Directory:", os.getcwd())

In [ ]:
# load baseline data
sgg_time = pd.read_csv('한강공원별시군구_날짜순.csv')
sgg_time

In [ ]:
# Define the file paths
file_paths = {
    '2020': '기간별_일평균_대기환경_정보_2020년.csv',
    '2021': '기간별_일평균_대기환경_정보_2021년.csv',
    '2022': '기간별_일평균_대기환경_정보_2022년.csv',
    '2023': '기간별_일평균_대기환경_정보_2023년.csv'
}

# Dictionary to hold dataframes
dataframes = {}

# Load each file and display head and tail
for year, file_path in file_paths.items():
    df = pd.read_csv(file_path, encoding='cp949')
    dataframes[year] = df
    print(f"Data for {year} - Head:")
    print(df.head())
    print(f"\nData for {year} - Tail:")
    print(df.tail())
    print("\n" + "="*40 + "\n")

In [ ]:
air_20 = dataframes['2020']
air_21 = dataframes['2021']
air_22 = dataframes['2022']
air_23 = dataframes['2023']

- Rename

In [ ]:
new_column_names = {
    '측정일시' : 'DATE',
    '측정소명' : 'sggnm',
    '이산화질소농도(ppm)' : 'NO2',
    '오존농도(ppm)' : 'O3',
    '일산화탄소농도(ppm)' : 'CO',
    '아황산가스농도(ppm)' : 'SO2',
    '미세먼지농도(㎍/㎥)' : 'PM10',
    '초미세먼지농도(㎍/㎥)' : 'PM2.5'
}

new_column_names2 = {
    '측정일시' : 'DATE',
    '측정소명' : 'sggnm',
    '이산화질소농도(ppm)' : 'NO2',
    '오존농도(ppm)' : 'O3',
    '일산화탄소농도(ppm)' : 'CO',
    '아황산가스농도(ppm)' : 'SO2',
    '미세먼지(㎍/㎥)' : 'PM10',
    '초미세먼지(㎍/㎥)' : 'PM2.5'
}

air_20.rename(columns=new_column_names, inplace=True)
air_21.rename(columns=new_column_names, inplace=True)
air_22.rename(columns=new_column_names2, inplace=True)
air_23.rename(columns=new_column_names2, inplace=True)

In [ ]:
# Combine all data
air_all = pd.concat([air_20, air_21, air_22, air_23], ignore_index=True)
air_all.drop(['권역명'], axis=1, inplace=True)
air_all

In [ ]:
# Data structure
air_all.info()

In [ ]:
# Check Null
air_all.isnull().sum()

- Fill missing values

In [ ]:
# 인접한 구 정보
related_areas = {
    '강남구': ['광진구', '서초구', '성동구', '송파구', '용산구'],
    '강동구': ['광진구', '송파구'],
    '강북구': ['노원구', '도봉구', '성북구'],
    '강서구': ['마포구', '양천구', '영등포구'],
    '관악구': ['구로구', '금천구', '동작구', '서초구', '영등포구'],
    '광진구': ['강남구', '강동구', '동대문구', '성동구', '송파구', '중랑구'],
    '구로구': ['관악구', '금천구', '동작구', '양천구', '영등포구'],
    '금천구': ['관악구', '구로구'],
    '노원구': ['강북구', '도봉구', '성북구', '중랑구'],
    '도봉구': ['강북구', '노원구'],
    '동대문구': ['광진구', '성동구', '성북구', '종로구', '중구', '중랑구'],
    '동작구': ['관악구', '구로구', '서초구', '영등포구', '용산구'],
    '마포구': ['강서구', '서대문구', '영등포구', '용산구', '은평구', '중구'],
    '서대문구': ['마포구', '은평구', '종로구', '중구'],
    '서초구': ['강남구', '관악구', '동작구', '용산구'],
    '성동구': ['강남구', '광진구', '동대문구', '용산구', '종로구', '중구'],
    '성북구': ['강북구', '노원구', '동대문구', '종로구', '중랑구'],
    '송파구': ['강남구', '강동구', '광진구'],
    '양천구': ['강서구', '구로구', '영등포구'],
    '영등포구': ['강서구', '관악구', '구로구', '동작구', '마포구', '양천구', '용산구'],
    '용산구': ['강남구', '동작구', '마포구', '서초구', '성동구', '영등포구', '중구'],
    '은평구': ['마포구', '서대문구', '종로구'],
    '종로구': ['동대문구', '서대문구', '성동구', '성북구', '은평구', '중구'],
    '중구': ['동대문구', '마포구', '서대문구', '성동구', '용산구', '종로구'],
    '중랑구': ['광진구', '노원구', '동대문구', '성북구']
}

In [ ]:
# 결측치 처리 함수
def fill_missing_values(df, related_areas):
    df_filled = df.copy()
    for idx, row in df_filled[df_filled.isnull().any(axis=1)].iterrows():
        sggnm = row['sggnm']
        date = row['DATE']
        if sggnm in related_areas:
            related_sggnms = related_areas[sggnm]
            # 관련 구의 동일 날짜 데이터 필터링
            related_rows = df_filled[(df_filled['DATE'] == date) & (df_filled['sggnm'].isin(related_sggnms))]
            for col in ['NO2', 'O3', 'CO', 'SO2', 'PM10', 'PM2.5']:
                if pd.isnull(row[col]):
                    mean_value = related_rows[col].mean()
                    df_filled.at[idx, col] = mean_value
    return df_filled

# 결측치 채우기
air_filled = fill_missing_values(air_all, related_areas)
air_filled

In [ ]:
air_filled.info()

In [ ]:
# Check null
air_filled.isnull().sum()

- Convert `int` to `Datetime`

In [ ]:
# baseline data
sgg_time['DATE'] = pd.to_datetime(sgg_time['DATE'], format = '%Y-%m-%d')
sgg_time

In [ ]:
# air data
air_filled['DATE'] = pd.to_datetime(air_filled['DATE'], format = '%Y%m%d')
air_filled

- 한강공원별시군구_날짜순 + 대기환경

In [ ]:
merged_data = pd.merge(sgg_time, air_filled, on=['sggnm', 'DATE'], how='left')
merged_data

### **2. 날씨**

In [ ]:
# 관측소-시군구 데이터
df = pd.read_csv('관측소+시군구.csv')
df

In [ ]:
# load weather data
weather_data = pd.read_csv('OBS_AWS_DD_20240530205223.csv', encoding='cp949')
weather_data

In [ ]:
weather_data['지점명'] = weather_data['지점명'].apply(lambda x: x + '구')
weather_data

In [ ]:
# Data structure
weather_data.info()

In [ ]:
# Check Null
weather_data.isnull().sum()

- Rename

In [ ]:
new_column_names = {
    '지점명' : 'sggnm',
    '일시' : 'DATE',
    '평균기온(°C)' : 'avg_temp',
    '최저기온(°C)' : 'low_temp',
    '최고기온(°C)' : 'high_temp',
    '일강수량(mm)' : 'rain',
    '평균 풍속(m/s)' : 'avg_wind'
}

weather_data.rename(columns=new_column_names, inplace=True)
weather_data

- Drop `지점`

In [ ]:
weather_data.drop(['지점'], inplace=True, axis=1)
weather_data

- Convert `int` to `Datetime`

In [ ]:
weather_data['DATE'] = pd.to_datetime(weather_data['DATE'], format = '%Y-%m-%d')
weather_data

- Merge data : 한강공원별시군구_날짜순 + 대기환경 + 날씨
    - 결측치 채우기 위한 임시 병합

In [ ]:
merged_df = pd.merge(merged_data, weather_data, on = ['DATE', 'sggnm'], how = 'left')
merged_df

- Fill missing values

In [ ]:
# 인접한 구 정보
related_areas = {
    '강남구': ['광진구', '서초구', '성동구', '송파구', '용산구'],
    '강동구': ['광진구', '송파구'],
    '강북구': ['노원구', '도봉구', '성북구'],
    '강서구': ['마포구', '양천구', '영등포구'],
    '관악구': ['구로구', '금천구', '동작구', '서초구', '영등포구'],
    '광진구': ['강남구', '강동구', '동대문구', '성동구', '송파구', '중랑구'],
    '구로구': ['관악구', '금천구', '동작구', '양천구', '영등포구'],
    '금천구': ['관악구', '구로구'],
    '노원구': ['강북구', '도봉구', '성북구', '중랑구'],
    '도봉구': ['강북구', '노원구'],
    '동대문구': ['광진구', '성동구', '성북구', '종로구', '중구', '중랑구'],
    '동작구': ['관악구', '구로구', '서초구', '영등포구', '용산구'],
    '마포구': ['강서구', '서대문구', '영등포구', '용산구', '은평구', '중구'],
    '서대문구': ['마포구', '은평구', '종로구', '중구'],
    '서초구': ['강남구', '관악구', '동작구', '용산구'],
    '성동구': ['강남구', '광진구', '동대문구', '용산구', '종로구', '중구'],
    '성북구': ['강북구', '노원구', '동대문구', '종로구', '중랑구'],
    '송파구': ['강남구', '강동구', '광진구'],
    '양천구': ['강서구', '구로구', '영등포구'],
    '영등포구': ['강서구', '관악구', '구로구', '동작구', '마포구', '양천구', '용산구'],
    '용산구': ['강남구', '동작구', '마포구', '서초구', '성동구', '영등포구', '중구'],
    '은평구': ['마포구', '서대문구', '종로구'],
    '종로구': ['동대문구', '서대문구', '성동구', '성북구', '은평구', '중구'],
    '중구': ['동대문구', '마포구', '서대문구', '성동구', '용산구', '종로구'],
    '중랑구': ['광진구', '노원구', '동대문구', '성북구']
}

In [ ]:
# 결측치 처리 함수
def fill_missing_values(df, related_areas):
    df_filled = df.copy()
    for idx, row in df_filled[df_filled.isnull().any(axis=1)].iterrows():
        sggnm = row['sggnm']
        date = row['DATE']
        if sggnm in related_areas:
            related_sggnms = related_areas[sggnm]
            # 관련 구의 동일 날짜 데이터 필터링
            related_rows = df_filled[(df_filled['DATE'] == date) & (df_filled['sggnm'].isin(related_sggnms))]
            for col in ['avg_temp', 'low_temp', 'high_temp', 'rain', 'avg_wind']:
                if pd.isnull(row[col]):
                    mean_value = related_rows[col].mean()
                    df_filled.at[idx, col] = mean_value
    return df_filled

# 결측치 채우기
weather_filled = fill_missing_values(merged_df, related_areas)
weather_filled

In [ ]:
weather_filled.info()

In [ ]:
weather_filled.isnull().sum()

### **3. 시군구 데이터 병합**

In [ ]:
air_weather = weather_filled.groupby(['AREA_NM', 'DATE'], as_index=False)[['NO2', 'O3', 'CO', 'SO2', 'PM10', 'PM2.5', 'avg_temp', 'low_temp', 'high_temp', 'rain', 'avg_wind']].mean()
air_weather

In [ ]:
# 변수명 수정
new_column_names = {
    'AREA_NM' : 'hangang',
    'DATE' : 'date'
}

air_weather.rename(columns=new_column_names, inplace=True)
air_weather

## 최종 파일 병합 및 내보내기

In [ ]:
path = "C:/Users/ZzAa/Desktop/대학원 (24-1)/데이터마이닝/Project/Data/병합용"
os.chdir(path)

print("Current Working Directory:", os.getcwd())

# load final data
final_data = pd.read_csv('hangang+people.csv')
final_data

- Convert `int` to `datetime`

In [ ]:
final_data['date'] = pd.to_datetime(final_data['date'], format = '%Y-%m-%d')
final_data

In [ ]:
# final sgg data
air_weather

In [ ]:
# final dong data
population_income

In [ ]:
# 파일 병합
merged_data = pd.merge(final_data, air_weather, on=['hangang', 'date'], how='left')
merged_data = pd.merge(merged_data, population_income, on=['hangang', 'date'], how='left')
merged_data

- Export data

In [ ]:
merged_data.to_csv('hangang+people+air+weather+population+income.csv', index=False, encoding='utf-8-sig')